package LinkedList;

import java.util.Scanner;

/**
 * This class is responsible for obtaining the input from the user. It simply prompts
 * the user for input and then uses a scanner to obtain it.
 *
 * @author Renaldo Musto
 * @version 1.0.0
 * @since 2025-09-30
 */

public class GetUserInput {

    /**
     * This is the default constructor for the GetUserInput class.
     */
    public GetUserInput() {
        // The constructor is intentionally empty.
    }

    /**
     * This method implements the necessary code to prompt the user
     * and accept their input.
     *
     * @param scanner this is the scanner object that collects the user input
     *                which was generated by main
     * @return the user input as a String
     */
    // Scanner is initialized in Main
    public String getUserInput(Scanner scanner) {
        System.out.println("Enter a list of numbers separated by spaces:");
        return scanner.nextLine();
    }
}
